name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GATSBY_ORIGIN: https://www.lapi.tokyo
      GATSBY_API_URL: https://api.lapi.tokyo/graphql
      GATSBY_AUTH_CLIENT_ID: kf3VdHdPiYSFlJhiBPDIj1cRDezM1Cjo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
          check-latest: true
      - run: npm ci
      - run: npm run build
      - run: npm run lint-test
      - run: npm run format-test
      - run: npm test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: dragoneena12/lapi-website-gatsby:latest
